# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-getuser
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: java-getuser
  template:
    metadata:
      labels:
        app: java-getuser
    spec:
      containers:
        - name: java-getuser
          image: noelnondoh/java-getuser:latest  # Replace with your Docker image
          ports:
            - containerPort: 9898  # Make sure this matches the exposed port in your Dockerfile



